apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbird-ingressroute
  labels: {{- include "common.labels" (dict "name" "netbird" "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ .Values.tls.secretName }}
  routes:
    - kind: Rule
      match: Host(`{{ include "netbird.host" . }}`) && (PathPrefix(`/management.ManagementService`) || PathPrefix(`/signalexchange.SignalExchange`))
      services:
        - kind: Service
          name: {{ .Values.server.name }}
          port: {{ .Values.server.port }}
          scheme: h2c
    - kind: Rule
      match: Host(`{{ include "netbird.host" . }}`) && (PathPrefix(`/api`) || PathPrefix(`/oauth2`) || PathPrefix(`/ws-proxy`) || PathPrefix(`/relay`))
      services:
        - kind: Service
          name: {{ .Values.server.name }}
          port: {{ .Values.server.port }}
    - kind: Rule
      match: Host(`{{ include "netbird.host" . }}`)
      services:
        - kind: Service
          name: {{ .Values.dashboard.name }}
          port: {{ .Values.dashboard.port }}

