apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.name }}-config
  labels: {{- include "common.labels" (dict "name" .Values.server.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
stringData:
  config.yaml: |
    server:
      listenAddress: ":{{ .Values.server.port }}"
      exposedAddress: "https://{{ include "netbird.host" . }}:443"
      stunPorts:
        - {{ .Values.server.stunPort }}
      metricsPort: 9090
      healthcheckAddress: ":9000"
      logLevel: "info"
      logFile: "console"
      authSecret: "{{ .Values.server.relayAuthSecret }}"
      dataDir: {{ .Values.server.dataDir }}

      auth:
        issuer: "https://{{ include "netbird.host" . }}/oauth2"
        signKeyRefreshEnabled: true
        dashboardRedirectURIs:
          - "https://{{ include "netbird.host" . }}/nb-auth"
          - "https://{{ include "netbird.host" . }}/nb-silent-auth"
        cliRedirectURIs:
          - "http://localhost:53000/"

      reverseProxy:
        trustedHTTPProxies:
          - "0.0.0.0/0"

      store:
        engine: "sqlite"
        encryptionKey: {{ .Values.encryptionKey }}
